# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44ccff53552c652da50ccf4eb68538e9ace0ff2c805f298ca7a58e1519ff9ca36e5b121ffbf43cea411f875d3a0bff1a47236fc4f00ef3bfbf3931365bb6e448

test:
  secret_key_base: d9d59c12d672f317fa2c0af80fc30d6c7ca78b03d27a7ca23317d6568dd3bae411faf313e9d42f1e9c83e3f8b1e5aaad7be1e4cb639d6f7a52a3e883e2257f96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
